Jaxb export import
todor-tibor/Library pull request #34
Opened 2017-03-08 07:32 UTC by TerezSipos

Megy minden tab-re (Role, User, Author, Publisher, Publication, Borrow es BorrowLate) az import export
Apro valtozasok a User validalasanal es updatenel (ha nincs megadva password akkor marad a regi)

2017-03-08 09:36 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			System.out.println(type);
oh sysout. torolni

2017-03-08 09:36 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			System.out.println(xml.getClass());
torolni

2017-03-08 09:36 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			System.out.println(wrapper.getClass());
torolni

2017-03-08 09:37 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			e.printStackTrace();
logolni az exceptiont

2017-03-08 09:37 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			throw new IllegalArgumentException("import.fail");
ez biztos hogy IllegalArgument ?

2017-03-08 09:38 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			throw new IllegalArgumentException("export.fail");
logolni az exceptiont

2017-03-08 09:38 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/util/JAXB.java
> +			throw new IllegalArgumentException("export.fail");
a tovabb dobott exception biztos hogy IllegalArgument ?

2017-03-08 09:39 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/ImportExportMB.java
> +			System.out.println("import type: " + this.clazz);
torolni

2017-03-08 09:41 UTC, todor-tibor requested changes
needs work

2017-03-08 11:01 UTC, TerezSipos commented
Csinaltam egy sajat exception-t az IllegalArgument helyett, kivettem a sysoutokat (bocsi miadtuk)

2017-03-09 07:23 UTC, todor-tibor approved these changes

2017-03-09 07:36 UTC, merged