Pdf unified
todor-tibor/Library pull request #35
Opened 2017-03-08 08:34 UTC by KatalinKis

PDF export feature for borrowings, users, publications, roles, authors, publishers.

2017-03-08 09:19 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/UnifiedModel.java
> +	public UnifiedModel(final String descriptor, final String description, final Map<String, String> details,
javadoc

2017-03-08 09:20 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/UnifiedModel.java
> +	public UnifiedModel() {
ha ez ures akkor nincs ertelme deklaralni

2017-03-08 09:21 UTC, todor-tibor commented on library-jpa/src/main/java/com/edu/library/model/UnifiedModel.java
> +	public String getDescriptor() {
javadoc

2017-03-08 09:23 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/DataExctractor.java
> +		listOfConvertedPublications.forEach(u -> System.out.println(u.toString()));
ohhh, torolni

2017-03-08 09:23 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/DataExctractor.java
> +		listOfConvertedPublications.forEach(u -> System.out.println(u.toString()));
torolni

2017-03-08 09:23 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/DataExctractor.java
> +		listOfConvertedPublications.forEach(u -> System.out.println(u.toString()));
torolni

2017-03-08 09:23 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/DataExctractor.java
> +		listOfConvertedPublications.forEach(u -> System.out.println(u.toString()));
torolni

2017-03-08 09:23 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/DataExctractor.java
> +		listOfConvertedPublications.forEach(u -> System.out.println(u.toString()));
torolni

2017-03-08 09:24 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/DataExctractor.java
> +		listOfConvertedPublications.forEach(u -> System.out.println(u.toString()));
es itt is

2017-03-08 09:25 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/PdfExporter.java
> +	public java.util.List<Publication> getPublications() {
javadoc

2017-03-08 09:28 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/PdfExporter.java
> +				.forEach(System.out::println);
ezt is lehet torolni

2017-03-08 09:31 UTC, todor-tibor commented on library-web/src/main/java/com/edu/library/util/PdfExporterMB.java
> +package com.edu.library.util;
Ez akkor ugyanaz mint a PdfExporter.java ? Egyiket lehet torolni.

2017-03-08 09:33 UTC, todor-tibor requested changes
needs work

2017-03-08 11:38 UTC, TerezSipos commented
Katinak egy kis problemaja van a gepevel, de megvannak a kert valtoztatasok. (Paralell programing-ot csinalunk amig tud beszelni Demeter Zoltannal)

2017-03-09 07:09 UTC, todor-tibor approved these changes
review ok

2017-03-09 07:10 UTC, merged